version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    depends_on:
      - api-search
  api-search:
    build:
      context: .
      dockerfile: "ApiSearch/Dockerfile"
    depends_on:
      - load-balancer
    volumes:
      - "C:\\University Work\\SearchEngine-Baseline\\EnronMini:/data"
    deploy:
      replicas: 5
  web-ui:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    ports:
      - 9001:80
