version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - 9000:80
  api-search:
    build:
      context: .
      dockerfile: "ApiSearch/Dockerfile"
    ports:
      - 9001:80
    volumes:
      - "C:\\University Work\\SearchEngine-Baseline\\EnronMiniSource:/data"
    deploy:
      replicas: 1
    depends_on:
      - load-balancer
  web-ui:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    ports:
      - 9002:80
