version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: "ApiSearch/Dockerfile"
    volumes:
      - "C:\\University Work\\SearchEngine-Baseline\\EnronMini:/data"
    deploy:
      replicas: 5
  web:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    ports:
      - 9001:80
