version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    image: nitrozeus1/search-engine-load-balancer:${DEPLOY_NUMBER}
    ports: 
      - 9020:80
  api-search:
    build:
      context: .
      dockerfile: "ApiSearch/Dockerfile"
    image: nitrozeus1/api-search:${DEPLOY_NUMBER}
    volumes: #link your own database root here
      - "C:/EnronMini:/data"
    deploy:
      replicas: 3
    depends_on:
      - load-balancer
  web-ui:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    image: nitrozeus1/web-search:${DEPLOY_NUMBER} 
    ports:
      - 9023:80
